version: "3.8"
services:
  web:
    build: .
    volumes:
      - "./:/app"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      APP_UVICORN_OPTIONS: "--reload --reload-dir app --host 0.0.0.0 --port=8000"
    env_file:
      - .env

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    command: "python -u consumer.py"

  postgres:
    image: postgres:12.9
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  postgres:
