"""autogenerate shop uuid

Revision ID: f7e621e7da87
Revises: 14f4fe71ae85
Create Date: 2024-09-19 17:16:20.941401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e621e7da87'
down_revision: Union[str, None] = '14f4fe71ae85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'owner',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'owner',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
