"""upd shop4

Revision ID: 3faec9f2fde1
Revises: c5edcd5d1582
Create Date: 2024-09-21 00:08:38.306491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faec9f2fde1'
down_revision: Union[str, None] = 'c5edcd5d1582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
