"""autoincrement category id

Revision ID: 14f4fe71ae85
Revises: 7729f4fc7df3
Create Date: 2024-09-19 16:44:08.791036

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14f4fe71ae85'
down_revision: Union[str, None] = '7729f4fc7df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'wishlist', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_column('wishlist', 'user_id')
    # ### end Alembic commands ###
