"""update orderProduct model id to uuid

Revision ID: be466037694a
Revises: 37333aa6c942
Create Date: 2024-09-24 17:46:54.757042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be466037694a'
down_revision: Union[str, None] = '37333aa6c942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'id')
    # ### end Alembic commands ###
