"""upd shop9

Revision ID: 9d90fa9f3926
Revises: 7b74c94f8647
Create Date: 2024-09-23 21:42:29.697862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d90fa9f3926'
down_revision: Union[str, None] = '7b74c94f8647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='product_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_category_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_category_pkey')
    )
    # ### end Alembic commands ###
