"""upd shop

Revision ID: 0b55f6790e5d
Revises: f7e621e7da87
Create Date: 2024-09-20 22:28:35.057309

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b55f6790e5d'
down_revision: Union[str, None] = 'f7e621e7da87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_constraint('shop_owner_fkey', 'shop', type_='foreignkey')
    op.create_foreign_key(None, 'shop', 'user', ['owner_id'], ['id'])
    op.drop_column('shop', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('owner', sa.UUID(),
                  autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'shop', type_='foreignkey')
    op.create_foreign_key('shop_owner_fkey', 'shop', 'user', ['owner'], ['id'])
    op.drop_column('shop', 'owner_id')
    # ### end Alembic commands ###
