"""update orderProduct model

Revision ID: 9e51b9fc07db
Revises: 6dec7f5d432f
Create Date: 2024-09-24 17:24:42.997883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e51b9fc07db'
down_revision: Union[str, None] = '6dec7f5d432f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
